### PR TITLE
Fixes bug setting expiration period for token.

### PR DESCRIPTION
**Pull request by zjuanma**
There is a bug when setting expiration period for token, It must be now + exp.

### CODE REVIEW

**Comment by devArtoria** [comment]
Thanks for PR! I'll review your PR soon. (my country is midnight)

**Comment by zjuanma** [comment]
@devArtoria  can you release a new version in npm?

**Comment by devArtoria** [comment]
Oh, I forgot to publish this changes! 😂😂 I'll publish it to pypi right now. 
thanks for remind,  @zjuanma

**Comment by devArtoria** [comment]
Check about latest release 1.1.2
https://pypi.org/project/Flask-GraphQL-Auth/

**Pull request merged**
